language: node_js
node_js:
    - "node"
install:
    - npm install
script:
    - npm run build
deploy:
    provider: firebase
    token:
        secure: $FIREBASE_TOKEN
    project: "countries-of-the-world-25202"