language: node_js
node_js:
    - "12"
install:
    - npm install -g firebase-tools
script:
    - echo "deploying"
deploy:
    provider: firebase
    token: $FIREBASE_TOKEN
    edge: true # opt in to dpl v2
    project: countries-of-the-world-25202