language: node_js
node_js:
    - "node"
install:
    - npm install
script:
    - npm run build
after_success:
    - echo Starting deploy
    - firebase deploy --project countries-of-the-world-25202 --token $FIREBASE_TOKEN